use_frameworks!

target 'EasyTransitions_Example' do
  pod 'EasyTransitions', :path => '../'

  target 'EasyTransitions_Tests' do
    inherit! :search_paths
  end
end

target 'EasyTransitionTVOS' do
  pod 'EasyTransitions', :path => '../'
end
